# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"

ZSH_TMUX_AUTOSTART=true

# Enable profiling zsh
# zmodload zsh/zprof

# Set max number of open file descriptors for idea
ulimit -n 4096

# Add timestamp to history
HIST_STAMPS="yyyy-mm-dd"

# export TERM="screen-256color"
export LESS="-RFX"
export EDITOR="code --wait --new-window"
export ZSH="$HOME/.oh-my-zsh"

# bashcompinit
autoload bashcompinit
bashcompinit

# zsh configuration
plugins=(
    asdf
    aws
    docker
    docker-compose
    git
    helm
    kubectl
    op
    tmux
    vault
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Only run compinit once a day
# autoload -Uz compinit
# for dump in ~/.zcompdump(N.mh+24); do
#   compinit
# done
# compinit -C

# Path variable
export PATH=${PATH}:${HOME}/.krew/bin:$PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# No idea. For mac?
# fpath=($fpath ~/.zsh/completion)

# Golang settings
GOV=$(asdf where golang)
export GOROOT=$GOV/go
export GOPATH="${HOME}/go"
export PATH="${PATH}:${GOPATH}/bin:${GOROOT}/bin"

# Output profiling info
# zprof
