
- name: Install VLC through Snap
  become: true
  community.general.snap:
    name:
      - vlc

- name: Create VLC config directory
  ansible.builtin.file:
    dest: ~/snap/vlc/common/
    state: directory
    mode: 0755

- name: Symlink the VLC config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/vlc/files/vlcrc"
    dest: ~/snap/vlc/common/vlcrc
    force: true
    state: link

# VLC replaces the symlink with a new file. Revoke write permissions to force 
# error that reminds changing the file in the role.
- name: Revoke write permissions from VLC config file
  ansible.builtin.file:
    path: "{{ playbook_dir }}/roles/vlc/files/vlcrc"
    mode: 0444

- name: Set VLC as default app
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/vlc/files/mimeapps.list"
    dest: ~/.config/mimeapps.list
    mode: 0600
