- name: Install VLC through Snap
  become: true
  community.general.snap:
    name:
      - vlc

- name: Symlink the VLC config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/vlc/files/vlcrc"
    dest: ~/snap/vlc/common/vlcrc
    force: true
    state: link

# VLC replaces the symlink with a new file. Revoke write permissions to force 
# error that reminds changing the file in the role.
- name: Revoke write permissions from VLC config file
  ansible.builtin.file:
    path: "{{ playbook_dir }}/roles/vlc/files/vlcrc"
    mode: 0444

# https://askubuntu.com/questions/1030281/change-default-applications-from-script
- name: Set VLC as default application for video files
  ansible.builtin.replace:
    path: ~/.config/mimeapps.list
    regexp: org\.gnome\.Totem\.desktop
    replace: vlc_vlc.desktop
