- hosts: all

  roles:
    - role: apt
      tags: apt
    - role: asdf
      tags: asdf
    - role: git
      tags: git
    - role: gnome
      tags: gnome
    - role: google-chrome
      tags: google-chrome
    - role: resolved
      tags: resolved
    - role: samba
      tags: samba
    - role: snap
      tags: snap
    - role: ssh
      tags: ssh
    - role: sudoers
      tags: sudoers
    - role: tmux
      tags: tmux
    - role: vscode
      tags: vscode
    - role: zsh
      tags: zsh
