- hosts: all

  roles:
    - role: apt
      tags: apt
    - role: asdf
      tags: asdf
    - role: git
      tags: git
    - role: gnome
      tags: gnome
    - role: google-chrome
      tags: google-chrome
