- name: Install keyring software
  apt:
    name:
      - gnome-keyring
      - keychain
      - seahorse

- name: Create SSH config
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory
    mode: 0700

- name: Symlink the ssh config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/ssh/files/config"
    dest: ~/.ssh/config
    force: true
    state: link

- name: Download SSH keys from 1password
  ansible.builtin.include_tasks: keys.yaml
  vars:
    ssh_key: "{{ item }}"
  loop: "{{ ssh_keys }}"
