- name: Install Powerlevel10K theme for Oh My Zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/themes/powerlevel10k
    depth: 1

- name: Copy .Powerlevel10k config
  copy:
    src: p10k.zsh
    dest: ~/.p10k.zsh

- name: Create fonts directory
  ansible.builtin.file:
    dest: ~/.local/share/fonts/
    state: directory
    mode: 0755

- name: Install font for Powerlevel10k theme
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf?raw=true
    dest: ~/.local/share/fonts/Meslo LG S Regular Nerd Font Complete.ttf

  # Ref https://ncona.com/2019/11/configuring-gnome-terminal-programmatically/
- name: Get gsettings id of default profile in Terminal
  shell: gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
  register: profile_id

- name: Set font for default profile in Terminal
  shell: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{profile_id.stdout}}/ font 'MesloLGS Nerd Font 11'"

- name: Set color palette for default profile in Terminal
  shell: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{profile_id.stdout}}/ palette \"['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(45,112,195)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']\""
