- name: Install zsh
  become: true
  apt:
    name:
      - zsh

- name: Change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Copy .zshrc
  copy:
    src: zshrc
    dest: ~/.zshrc
