- name: Install zsh
  become: true
  apt:
    name:
      - zsh

- name: Change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Symlink the zshrc file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/zsh/files/zshrc"
    dest: ~/.zshrc
    force: true
    state: link
