- name: Configure keyboard shortcuts
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
      - key: /org/gnome/desktop/wm/keybindings/begin-move
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/begin-resize
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/maximize
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-corner-ne
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-corner-nw
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-corner-se
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-corner-sw
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-monitor-down
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-monitor-left
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-monitor-right
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-monitor-up
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-1
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-10
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-11
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-12
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-2
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-3
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-4
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-5
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-6
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-7
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-8
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-9
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-down
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-last
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-left
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-right
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/move-to-workspace-up
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-group
        value: "['<Super>Above_Tab']"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-1
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-10
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-11
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-12
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-2
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-3
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-4
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-5
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-6
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-7
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-8
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-9
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-last
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-left
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-right
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
        value: "@as []"
      - key: /org/gnome/desktop/wm/keybindings/unmaximize
        value: "@as []"
      - key: /org/gnome/mutter/keybindings/toggle-tiled-left
        value: "@as []"
      - key: /org/gnome/mutter/keybindings/toggle-tiled-right
        value: "@as []"
