- name: Install Git
  apt:
    name:
      - git

- name: Symlink the gitconfig file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/git/files/gitconfig"
    dest: ~/.gitconfig
    force: true
    state: link
