- name: Disable DNSStubListener
  become: true
  replace:
    path: /etc/systemd/resolved.conf
    regexp: \#DNSStubListener=yes
    replace: DNSStubListener=no
  register: resolved_conf

- name: Restart systemd resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when: resolved_conf.changed
