- name: Install tmux
  become: true
  ansible.builtin.apt:
    name:
      - tmux

- name: Symlink the tmux config file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/tmux/files/tmux.conf"
    dest: ~/.tmux.conf
    force: true
    state: link
